version: "3"
services:
  app:
    container_name: serverPB
    restart: always
    build: .
    ports:
      - "8080:4000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - /app/backend/node_modules
      - .:/app/backend:delegated
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - "/Users/${USER}/data:/data/db"
    ports:
      - "27017:27017"
